version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: app_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_test
      POSTGRES_PASSWORD: admin_test_pwd
      POSTGRES_DB: deux_order_management_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: