name: Deux Orders Workflow

on:
  push:
    branches: [ main, fix_cicd_workflow ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ASPNETCORE_ENVIRONMENT: Development
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_ISSUER: "DeuxOrders"
      JWT_AUDIENCE: "DeuxOrders"
      Jwt__SECRET: ${{ secrets.JWT_SECRET }}
      Jwt__Issuer: "DeuxOrders"
      Jwt__Audience: "DeuxOrders"

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Use dotnet 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install dependencies and build
      run: |
        dotnet restore
        dotnet build --no-restore

    - name: Run Integration Tests
      run: |
        if [ -z "$JWT_SECRET" ]; then
          echo "::error::JWT_SECRET não encontrada! Verifique o Repository Secrets do GitHub."
          exit 1
        fi
        echo "JWT_SECRET detectada (Tamanho: ${#JWT_SECRET} caracteres)."
        dotnet test --no-build --verbosity normal
