name: Deux Orders Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Use dotnet 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Install dependencies and build
      run: |
        dotnet restore
        dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal